"""empty message

Revision ID: 016f0a1be96d
Revises: 738e3011c939
Create Date: 2021-01-12 22:42:05.479088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '016f0a1be96d'
down_revision = '738e3011c939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.drop_column('users', 'image_file')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_file', mysql.VARCHAR(length=20), nullable=False))
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
